output_root: '../'
pytorch_data_dir: '../datasets/'
experiment_name: "exp01"
log_dir: "../logs/"
res: 320
batch_size: 16
num_workers: 0
run_crf: False
run_prediction: True
dark_mode: True
use_ddp: False

dataset_name: "directory"
dir_dataset_name: "liverUSfiltered"
dir_dataset_n_classes: 6
model_type: "vit_base"

model_paths:
  #- "../saved_models/cocostuff27_vit_base_5.ckpt"

hydra:
  run:
    dir: "../logs"
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
