output_root: '../'
pytorch_data_dir: '../datasets/'
experiment_name: "exp01"
log_dir: "../logs"
azureml_logging: True
submitting_to_aml: False

# Loader params
num_workers: 0
max_steps: 1700
batch_size: 32
max_epochs: 100

num_neighbors: 5
dataset_name: "directory"
#dataset_name: "potsdam"

# Used if dataset_name is "directory"
dir_dataset_name: "liverUSfiltered"
dir_dataset_n_classes: 6

has_labels: True
crop_type: None
#crop_type: "five"
crop_ratio: .5
res: 224
loader_crop_type: "center"

# Model Params
extra_clusters: 0
use_true_labels: False
use_recalibrator: False
model_type: "vit_base"
arch: "dino"
use_fit_model: False
dino_feat_type: "feat"
projection_type: "nonlinear"
dino_patch_size: 8
granularity: 1
continuous: True
dim: 90
dropout: True
zero_clamp: True

lr: 5e-5
pretrained_weights: ~
use_salience: False
stabalize: False
stop_at_zero: True

# Feature Contrastive params
pointwise: True
feature_samples: 11
neg_samples: 5
aug_alignment_weight: 0.0

correspondence_weight: 1.0

# USLiver vit_base
neg_inter_weight: 0.11          #λ-rand
pos_inter_weight: 0.93          #λ-knn
pos_intra_weight: 0.12          #λ-self
neg_inter_shift: 0.93           #b-rand   .64
pos_inter_shift: 0.21           #b-knn    .11
pos_intra_shift: 0.21           #b-self   .13

# USLiver vit_small
#neg_inter_weight: 0.62         #λ-rand
#pos_inter_weight: 0.29         #λ-knn
#pos_intra_weight: 0.68         #λ-self
#neg_inter_shift: 0.64          #b-rand
#pos_inter_shift: 0.02          #b-knn
#pos_intra_shift: 0.02          #b-self

# IAROA vit small 1/31/22
#neg_inter_weight: 0.63
#pos_inter_weight: 0.25
#pos_intra_weight: 0.67
#neg_inter_shift: 0.46
#pos_inter_shift: 0.12
#pos_intra_shift: 0.18

# Potsdam vit small 1/31/22
#neg_inter_weight: 0.63
#pos_inter_weight: 0.25
#pos_intra_weight: 0.67
#neg_inter_shift: 0.46
#pos_inter_shift: 0.02
#pos_intra_shift: 0.08

# Cocostuff27 vit small 1/31/22
#neg_inter_weight: 0.63
#pos_inter_weight: 0.25
#pos_intra_weight: 0.67
#neg_inter_shift: 0.66
#pos_inter_shift: 0.02
#pos_intra_shift: 0.08

# Cocostuff27 10/3 vit_base
#neg_inter_weight: 0.1538476246415498
#pos_inter_weight: 1
#pos_intra_weight: 0.1
#neg_inter_shift: 1
#pos_inter_shift: 0.2
#pos_intra_shift: 0.12

# Cocostuff27 10/3 vit_small
#neg_inter_weight: .63
#pos_inter_weight: .25
#pos_intra_weight: .67
#neg_inter_shift: .16
#pos_inter_shift: .02
#pos_intra_shift: .08

# Cocostuff27 10/3 moco
#neg_inter_weight: .63
#pos_inter_weight: .25
#pos_intra_weight: .67
#neg_inter_shift: .26
#pos_inter_shift: .36
#pos_intra_shift: .32

#pos_inter_shift: .12
#pos_intra_shift: .18

# Cocostuff27
#neg_inter_weight: .72
#pos_inter_weight: .80
#pos_intra_weight: .29
#neg_inter_shift: .86
#pos_inter_shift: .04
#pos_intra_shift: .34

# Cityscapes 10/3
#neg_inter_weight: 0.9058762625226623
#pos_inter_weight: 0.577453483136995
#pos_intra_weight: 1
#neg_inter_shift: 0.31361241889448443
#pos_inter_shift: 0.1754346515479633
#pos_intra_shift: 0.45828472207

# Cityscapes
#neg_inter_weight: .72
#pos_inter_weight: .18
#pos_intra_weight: .46
#neg_inter_shift: .25
#pos_inter_shift: .20
#pos_intra_shift: .25

rec_weight: 0.0
repulsion_weight: 0.0

# CRF Params
crf_weight: 1.0
alpha: .5
beta: .15
gamma: .05
w1: 10.0
w2: 3.0
shift: 0.00
crf_samples: 1000
color_space: "rgb"

reset_probe_steps: ~

# Logging params
n_images: 5
scalar_log_freq: 10
checkpoint_freq: 50
val_freq: 100
hist_freq: 100


hydra:
  run:
    dir: "../logs"
    #dir: "."
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
